WebApplication0523mvc/Models/PurchaseOrder.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication0523mvc.Models
{
    public class PurchaseOrder
    {
        [Display(Name = "清单ID")]
        public int ID { get; set; }

        public string EmployeeName { get; set; }

        [Display(Name = "销售日期")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required]
        public DateTime Date { get; set; }

        [Display(Name = "顾客姓名")]
        [Required]
        public string CustomerName { get; set; }

        [Display(Name = "账单邮寄地址")]
        [Required]
        public string BillingAddress { get; set; }

        [Display(Name = "所购商品")]
        [Required]
        public string Product { get; set; }

        [Display(Name = "销售金额")]
        [DataType(DataType.Currency)]
        [Required]
        public decimal Total { get; set; }

        [Display(Name = "订单状况")]
        public string isClosed { get; set; }
    }
}

WebApplication0523mvc/Controllers/PurchaseOrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication0523mvc.Models;

namespace WebApplication0523mvc.Controllers
{
    [Authorize]
    public class PurchaseOrdersController : Controller
    {
        private MovieDBContext db = new MovieDBContext();

        // GET: PurchaseOrders
        public ActionResult Index(string searchID)
        {
            var orders = from l in db.PurchaseOrders
                            select l;
            orders = orders.Where(s => s.EmployeeName.Equals(User.Identity.Name));

            if (!string.IsNullOrEmpty(searchID))
            {
                if (searchID.Equals("all"))
                    return View(orders);

                try
                {
                    int id = int.Parse(searchID);
                    orders = orders.Where(s => s.ID.Equals(id));
                }
                catch (Exception e)
                {
                    Response.Write("<script>alert('请输入数字!')</script>");
                    return View(orders);
                }
                if (orders.Count() == 0)
                {
                    Response.Write("<script>alert('销售清单ID不存在!')</script>");
                    return View(orders);
                }
                return View(orders);
            }
            else
                return View(orders);
        }

        // GET: PurchaseOrders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PurchaseOrder purchaseOrder = db.PurchaseOrders.Find(id);
            if (purchaseOrder == null)
            {
                return HttpNotFound();
            }
            return View(purchaseOrder);
        }

        // GET: PurchaseOrders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PurchaseOrders/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Date,CustomerName,BillingAddress,Product,Total")] PurchaseOrder purchaseOrder)
        {
            purchaseOrder.EmployeeName = User.Identity.Name;

            if (ModelState.IsValid)
            {
                db.PurchaseOrders.Add(purchaseOrder);
                db.SaveChanges();
                return RedirectToAction("Details",new { id = purchaseOrder.ID});
            }

            return View(purchaseOrder);
        }

        // GET: PurchaseOrders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PurchaseOrder purchaseOrder = db.PurchaseOrders.Find(id);
            if (purchaseOrder == null)
            {
                return HttpNotFound();
            }
            if (purchaseOrder.isClosed != null)
            {
                Response.Write("<script>alert('交易已关闭!')</script>");
                return RedirectToAction("Index");
            }
            //防止修改他人信息
            if (!purchaseOrder.EmployeeName.Equals(User.Identity.Name))
            {
                return RedirectToAction("Index");
            }
            return View(purchaseOrder);
        }

        // POST: PurchaseOrders/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Date,CustomerName,BillingAddress,Product,Total")] PurchaseOrder purchaseOrder)
        {
            purchaseOrder.EmployeeName = User.Identity.Name;

            if (ModelState.IsValid)
            {
                db.Entry(purchaseOrder).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(purchaseOrder);
        }

        // GET: PurchaseOrders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PurchaseOrder purchaseOrder = db.PurchaseOrders.Find(id);
            if (purchaseOrder == null)
            {
                return HttpNotFound();
            }
            //防止修改他人信息
            if (!purchaseOrder.EmployeeName.Equals(User.Identity.Name))
            {
                return RedirectToAction("Index");
            }
            return View(purchaseOrder);
        }

        // POST: PurchaseOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PurchaseOrder purchaseOrder = db.PurchaseOrders.Find(id);
            db.PurchaseOrders.Remove(purchaseOrder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication0523mvc/Views/PurchaseOrders/Create.cshtml
@model WebApplication0523mvc.Models.PurchaseOrder

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>添加新记录</h1>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PurchaseOrder</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillingAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillingAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillingAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="添  加" class="btn btn-primary btn-lg" />
            </div>
        </div>
    </div>
}

<div>
    <input type="button" value="返回" onclick="location.href='@Url.Action("Index")'" class="btn btn-default" />
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication0523mvc/Views/PurchaseOrders/Delete.cshtml
@model WebApplication0523mvc.Models.PurchaseOrder

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>确认删除</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PurchaseOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmployeeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillingAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillingAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isClosed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isClosed)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="button" value="返回" onclick="location.href='@Url.Action("Index")'" class="btn btn-default" />
            <input type="submit" value="确认删除" class="btn btn-default" />
        </div>
    }
</div>

WebApplication0523mvc/Views/PurchaseOrders/Details.cshtml
@model WebApplication0523mvc.Models.PurchaseOrder

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>详细信息</h1>

<div>
    <h4>PurchaseOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BillingAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BillingAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isClosed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isClosed)
        </dd>

    </dl>
</div>
<p>
    <input type="button" value="返回" onclick="location.href='@Url.Action("Index")'" class="btn btn-default" />|
    @Html.ActionLink("修改", "Edit", new { id = Model.ID })
</p>

WebApplication0523mvc/Views/PurchaseOrders/Edit.cshtml
@model WebApplication0523mvc.Models.PurchaseOrder

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>修改信息</h1>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PurchaseOrder</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillingAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillingAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillingAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Product, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Product, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="确认修改" class="btn btn-primary btn-lg" />
            </div>
        </div>
    </div>
}

<div>
    <input type="button" value="返回" onclick="location.href='@Url.Action("Index")'" class="btn btn-default" />
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication0523mvc/Views/PurchaseOrders/Index.cshtml
@model IEnumerable<WebApplication0523mvc.Models.PurchaseOrder>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>销售清单</h1>

<p>
    <input type="button" value="添加新清单" onclick="location.href='@Url.Action("Create", "PurchaseOrders")'" class="btn btn-primary btn-lg" />

    @using (Html.BeginForm("Index", "PurchaseOrders", FormMethod.Get))
    {
    <p>
        请输入清单 ID :@Html.TextBox("SearchID")
        <input type="submit" value="搜 索" class="btn btn-default" /><br />
    </p>
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BillingAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Total)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isClosed)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmployeeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BillingAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Total)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.isClosed)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

<div>
    <input type="button" value="返回" onclick="location.href='@Url.Action("Index", "EmployeeMainPage")'" class="btn btn-default" />
</div>