WebApplication0523mvc/Models/EmployeeReport.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication0523mvc.Models
{
    public class EmployeeReport
    {
        [Display(Name = "报告类型")]
        public EMreporttype ReportType { get; set; }

        [Display(Name = "起始日期")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { get; set; }

        [Display(Name = "结束日期")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime EndDate { get; set; }

        [Display(Name = "项目编号")]
        public string Chargenumber { get; set; }

        [Display(Name = "累计工时")]
        public int TotalHour { get; set; }

        [Display(Name = "年度累计收入")]
        [DataType(DataType.Currency)]
        public decimal Salary { get; set; }

        [Display(Name = "年份")]
        public int Year { get; set; }

        [Display(Name ="员工姓名")]
        public string Name { get; set; }

        [Display(Name = "休假天数")]
        public int Vacation { get; set; }
    }

    public enum EMreporttype
    {
        [Display(Name = "累计工时")]
        TOTALHOUR,
        [Display(Name = "项目累计工时")]
        HOURSforPROJECT,
        [Display(Name = "剩余假期")]
        VACATION,
        [Display(Name = "当前全年工资")]
        YEARtoDATE
    }
}

WebApplication0523mvc/Controllers/EmployeeReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WebApplication0523mvc.Models;

namespace WebApplication0523mvc.Controllers
{
    [Authorize]
    public class EmployeeReportController : Controller
    {
        private static EmployeeReport EMPLOYEEREPORT = new EmployeeReport();
        private MovieDBContext db = new MovieDBContext();

        // GET: employeereport
        public ActionResult Index()
        {
            var ChargeNumList = new List<string>();
            var ChargeNumQry = from d in db.ChargeNumbers
                               orderby d.ID
                               select d.chargenumber;
            ChargeNumList.AddRange(ChargeNumQry.Distinct());
            ViewBag.ChargeNumList = new SelectList(ChargeNumList);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "ReportType,StartDate,EndDate,Chargenumber")] EmployeeReport employeereport)
        {
            var ChargeNumList = new List<string>();
            var ChargeNumQry = from d in db.ChargeNumbers
                               orderby d.ID
                               select d.chargenumber;
            ChargeNumList.AddRange(ChargeNumQry.Distinct());
            ViewBag.ChargeNumList = new SelectList(ChargeNumList);

            if (employeereport.ReportType == EMreporttype.TOTALHOUR)//累计工时
            {
                employeereport.TotalHour = countHour(employeereport);
                employeereport.Name = getName();
                EMPLOYEEREPORT = employeereport;
                return RedirectToAction("HourReport");
            }
            else if(employeereport.ReportType == EMreporttype.YEARtoDATE)//累计薪水
            {
                employeereport.Salary = countSalary(employeereport);
                employeereport.Year = employeereport.EndDate.Year;
                employeereport.Name = getName();
                EMPLOYEEREPORT = employeereport;
                return RedirectToAction("SalaryReport");
            }
            else if(employeereport.ReportType == EMreporttype.HOURSforPROJECT)//项目累计时间
            {
                if(employeereport.Chargenumber == null)
                {
                    Response.Write("<script>alert('请选择项目编号!')</script>");
                    return View(employeereport);
                }
                employeereport.TotalHour = countHoursForProject(employeereport);
                employeereport.Name = getName();
                EMPLOYEEREPORT = employeereport;
                return RedirectToAction("HoursForProject"); ;
            }
            else//剩余假期
            {
                employeereport.Vacation = countVacation();
                employeereport.Name = getName();
                EMPLOYEEREPORT = employeereport;
                return RedirectToAction("Vacation"); ;
            }
        }

        public ActionResult HourReport()
        {
            return View(EMPLOYEEREPORT);
        }

        public ActionResult SalaryReport()
        {
            return View(EMPLOYEEREPORT);
        }

        public ActionResult HoursForProject()
        {
            return View(EMPLOYEEREPORT);
        }

        public ActionResult Vacation()
        {
            return View(EMPLOYEEREPORT);
        }

        public ActionResult generateReport()
        {
            Print();
            return View(EMPLOYEEREPORT);
        }

        public void Print()
        {
            //命名导出表格的StringBuilder变量
            StringBuilder sHtml = new StringBuilder(string.Empty);

            //打印表头
            sHtml.Append("<table border=\"1\" width=\"100%\">");
            if (EMPLOYEEREPORT.ReportType == EMreporttype.TOTALHOUR)
            {
                sHtml.Append("<tr height=\"40\"><td colspan=\"4\" align=\"center\" style='font-size:24px'><b>员工累计工时报告" + "</b></td></tr>");
                sHtml.Append("<tr height=\"20\" align=\"center\"><td>起始日期</td><td>结束日期</td><td>员工姓名</td><td>累计工时</td></tr>");
                sHtml.Append("<tr height=\"20\" align=\"left\"><td>" + EMPLOYEEREPORT.StartDate + "</td><td>" + EMPLOYEEREPORT.EndDate + "</td><td>" + EMPLOYEEREPORT.Name + "</td><td>" + EMPLOYEEREPORT.TotalHour + "</td></tr>");
                sHtml.Append("</table>");
                ExportToExcel("application/ms-excel", EMPLOYEEREPORT.Name+"累计工时报告.xls", sHtml.ToString());
            }
            else if(EMPLOYEEREPORT.ReportType == EMreporttype.HOURSforPROJECT)
            {
                sHtml.Append("<tr height=\"40\"><td colspan=\"5\" align=\"center\" style='font-size:24px'><b>员工年度累计薪水报告" + "</b></td></tr>");
                sHtml.Append("<tr height=\"20\" align=\"center\"><td>起始日期</td><td>结束日期</td><td>员工姓名</td><td>项目编号</td><td>累计工时</td></tr>");
                sHtml.Append("<tr height=\"20\" align=\"left\"><td>" + EMPLOYEEREPORT.StartDate + "</td><td>" + EMPLOYEEREPORT.EndDate + "</td><td>" + EMPLOYEEREPORT.Name + "</td><td>" + EMPLOYEEREPORT.Chargenumber + "</td><td>"+EMPLOYEEREPORT.TotalHour+"</td></tr>");
                sHtml.Append("</table>");
                ExportToExcel("application/ms-excel", EMPLOYEEREPORT.Name+"项目累计工时报告.xls", sHtml.ToString());
            }
            else if(EMPLOYEEREPORT.ReportType == EMreporttype.VACATION)
            {
                sHtml.Append("<tr height=\"40\"><td colspan=\"4\" align=\"center\" style='font-size:24px'><b>剩余年假报告" + "</b></td></tr>");
                sHtml.Append("<tr height=\"20\" align=\"center\"><td>起始日期</td><td>结束日期</td><td>员工姓名</td><td>剩余年假</td></tr>");
                sHtml.Append("<tr height=\"20\" align=\"left\"><td>" + EMPLOYEEREPORT.StartDate + "</td><td>" + EMPLOYEEREPORT.EndDate + "</td><td>" + EMPLOYEEREPORT.Name + "</td><td>" + EMPLOYEEREPORT.Vacation + "</td></tr>");
                sHtml.Append("</table>");
                ExportToExcel("application/ms-excel", EMPLOYEEREPORT.Name + "剩余年假报告.xls", sHtml.ToString());
            }
            else
            {
                sHtml.Append("<tr height=\"40\"><td colspan=\"4\" align=\"center\" style='font-size:24px'><b>员工年度累计薪水报告" + "</b></td></tr>");
                sHtml.Append("<tr height=\"20\" align=\"center\"><td>年份</td><td>结束日期</td><td>员工姓名</td><td>年度累计收入</td></tr>");
                sHtml.Append("<tr height=\"20\" align=\"left\"><td>" + EMPLOYEEREPORT.Year + "</td><td>" + EMPLOYEEREPORT.EndDate + "</td><td>" + EMPLOYEEREPORT.Name + "</td><td>" + EMPLOYEEREPORT.Salary + "</td></tr>");
                sHtml.Append("</table>");
                ExportToExcel("application/ms-excel", EMPLOYEEREPORT.Name + "年度累计薪水报告.xls", sHtml.ToString());
            }


        }

        //输入HTTP头，然后把指定的流输出到指定的文件名，然后指定文件类型
        public void ExportToExcel(string FileType, string FileName, string ExcelContent)
        {
            System.Web.HttpContext.Current.Response.ContentType = FileType;
            System.Web.HttpContext.Current.Response.ContentEncoding = System.Text.Encoding.UTF8;
            System.Web.HttpContext.Current.Response.Charset = "utf-8";
            System.Web.HttpContext.Current.Response.AppendHeader("Content-Disposition", "attachment;filename=" + HttpUtility.UrlEncode(FileName, System.Text.Encoding.UTF8).ToString());

            System.IO.StringWriter tw = new System.IO.StringWriter();
            //System.Web.HttpContext.Current.Response.Output.Write(ExcelContent.ToString());
            /*乱码BUG修改 20140505*/
            System.Web.HttpContext.Current.Response.Write("<meta http-equiv=\"content-type\" content=\"application/ms-excel; charset=utf-8\"/>" + ExcelContent.ToString());
            System.Web.HttpContext.Current.Response.Flush();
            System.Web.HttpContext.Current.Response.End();
        }

        //计算累计工时
        private int countHour(EmployeeReport employeereport)
        {
            var timecards = from t in db.Timecards
                            where t.EmployeeName == User.Identity.Name && t.isSubmitted != null
                            select t;
            int totalhour = 0;
            foreach (Timecard t in timecards)
            {
                if (DateTime.Compare(t.Date, employeereport.StartDate) >= 0 && DateTime.Compare(t.Date, employeereport.EndDate) <= 0)
                    totalhour += t.Hours;
            }
            return totalhour;
        }

        //计算年度累计薪水
        private decimal countSalary(EmployeeReport employeereport)
        {
            var payrolls = from p in db.PayRolls
                           where p.EmployeeName == User.Identity.Name
                           select p;
            decimal totalsalary = 0;
            foreach (PayRoll p in payrolls)
            {
                if (p.PayDate.Year == employeereport.EndDate.Year && DateTime.Compare(p.PayDate, employeereport.EndDate) <= 0)
                    totalsalary += p.Salary;
            }
            return totalsalary;
        }

        //计算项目时间
        private int countHoursForProject(EmployeeReport employeereport)
        {
            var timecards = from t in db.Timecards
                            where t.EmployeeName == User.Identity.Name && t.isSubmitted != null
                            select t;
            timecards = timecards.Where(t => t.Chargenumber.Equals(employeereport.Chargenumber));
            int totalhour = 0;
            foreach (Timecard t in timecards)
            {
                if (DateTime.Compare(t.Date, employeereport.StartDate) >= 0 && DateTime.Compare(t.Date, employeereport.EndDate) <= 0)
                    totalhour += t.Hours;
            }
            return totalhour;
        }

        //计算假期
        private int countVacation()
        {

WebApplication0523mvc/Views/EmployeeReport/HourReport.cshtml
@model WebApplication0523mvc.Models.EmployeeReport


@{
    ViewBag.Title = "HourReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>员工累计工时报告</h1>

<p>
    <!--Html.ActionLink("Create New", "Create")-->

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalHour)
        </th>
        <th></th>
    </tr>


    <tr>
        <td>
            @Html.DisplayFor(model => model.StartDate)
        </td>
        <td>
            @Html.DisplayFor(model => model.EndDate)
        </td>
        <td>
            @Html.DisplayFor(model => model.Name)
        </td>
        <td>
            @Html.DisplayFor(model => model.TotalHour)
        </td>

    </tr>

</table>

<div style="text-align:center">
    <a class="btn btn-primary btn-lg" href="@Url.Action("generateReport","EmployeeReport")">下载报告</a>
</div>

<input type="button" value="返回" onclick="location.href='@Url.Action("Index")'" class="btn btn-default" />

WebApplication0523mvc/Views/EmployeeReport/HoursForProject.cshtml
@model WebApplication0523mvc.Models.EmployeeReport

@{
    ViewBag.Title = "HoursForProject";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>项目累计工时报告</h1>

<p>
    <!--Html.ActionLink("Create New", "Create")-->

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Chargenumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalHour)
        </th>
        <th></th>
    </tr>


    <tr>
        <td>
            @Html.DisplayFor(model => model.StartDate)
        </td>
        <td>
            @Html.DisplayFor(model => model.EndDate)
        </td>
        <td>
            @Html.DisplayFor(model => model.Name)
        </td>
        <td>
            @Html.DisplayFor(model => model.Chargenumber)
        </td>
        <td>
            @Html.DisplayFor(model => model.TotalHour)
        </td>

    </tr>

</table>

<div style="text-align:center">
    <a class="btn btn-primary btn-lg" href="@Url.Action("generateReport","EmployeeReport")">下载报告</a>
</div>

<input type="button" value="返回" onclick="location.href='@Url.Action("Index")'" class="btn btn-default" />

WebApplication0523mvc/Views/EmployeeReport/Index.cshtml
@model WebApplication0523mvc.Models.EmployeeReport


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>员工工作报告</h1>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Employee Report</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.ReportType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.ReportType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ReportType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Chargenumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Chargenumber, ViewBag.ChargeNumList as SelectList, "请选择项目编号", new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="生成报告" class="btn btn-primary btn-lg" />
            </div>
        </div>
    </div>
}

<div>
    <input type="button" value="返回" onclick="location.href='@Url.Action("Index", "EmployeeMainPage")'" class="btn btn-default" />
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplication0523mvc/Views/EmployeeReport/SalaryReport.cshtml
@model WebApplication0523mvc.Models.EmployeeReport


@{
    ViewBag.Title = "HourReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>年度累计薪水报告</h1>

<p>
    <!--Html.ActionLink("Create New", "Create")-->
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Year)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>
        <th></th>
    </tr>


    <tr>
        <td>
            @Html.DisplayFor(model => model.Year)
        </td>
        <td>
            @Html.DisplayFor(model => model.EndDate)
        </td>
        <td>
            @Html.DisplayFor(model => model.Name)
        </td>
        <td>
            @Html.DisplayFor(model => model.Salary)
        </td>

    </tr>

</table>

<div style="text-align:center">
    <a class="btn btn-primary btn-lg" href="@Url.Action("generateReport","EmployeeReport")">下载报告</a>
</div>

<input type="button" value="返回" onclick="location.href='@Url.Action("Index")'" class="btn btn-default" />

WebApplication0523mvc/Views/EmployeeReport/Vacation.cshtml
@model WebApplication0523mvc.Models.EmployeeReport

@{
    ViewBag.Title = "Vacation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>剩余年假报告</h1>

<p>
    <!--Html.ActionLink("Create New", "Create")-->

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vacation)
        </th>
        <th></th>
    </tr>


    <tr>
        <td>
            @Html.DisplayFor(model => model.StartDate)
        </td>
        <td>
            @Html.DisplayFor(model => model.EndDate)
        </td>
        <td>
            @Html.DisplayFor(model => model.Name)
        </td>
        <td>
            @Html.DisplayFor(model => model.Vacation)
        </td>

    </tr>

</table>

<div style="text-align:center">
    <a class="btn btn-primary btn-lg" href="@Url.Action("generateReport","EmployeeReport")">下载报告</a>
</div>

<input type="button" value="返回" onclick="location.href='@Url.Action("Index")'" class="btn btn-default" />